/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ap550
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Princiapal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CalculadoraButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AhorcadoButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        QuizzButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        MemoramaButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        CalculadoraMamasButton = new javax.swing.JButton();
        InfoCalEsqui = new javax.swing.JButton();
        InfoMemorama = new javax.swing.JButton();
        InfCalcPiteraMamas = new javax.swing.JButton();
        InfoQuizz = new javax.swing.JButton();
        InfAhorcado = new javax.swing.JButton();
        InfoButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 51, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CALCULADORA ESTEQUIOMÉTRICA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        CalculadoraButton.setBackground(new java.awt.Color(153, 153, 255));
        CalculadoraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/CalculadoraFresona.png"))); // NOI18N
        jPanel2.add(CalculadoraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("AHORCADO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 192, -1));

        AhorcadoButton.setBackground(new java.awt.Color(153, 153, 255));
        AhorcadoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horcaIcon.png"))); // NOI18N
        AhorcadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AhorcadoButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AhorcadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 80, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("QUIZZ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 62, -1));

        QuizzButton.setBackground(new java.awt.Color(153, 153, 255));
        QuizzButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Quizz.png"))); // NOI18N
        QuizzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizzButtonActionPerformed(evt);
            }
        });
        jPanel2.add(QuizzButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 400, 9));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 217, 310, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 400, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 400, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("MEMORAMA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 115, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 20, 220));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setToolTipText("");
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 10, 120));

        MemoramaButton.setBackground(new java.awt.Color(153, 153, 255));
        MemoramaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MemoramaIcon.png"))); // NOI18N
        MemoramaButton.setToolTipText("");
        jPanel2.add(MemoramaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 20, 230));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CALCULADORA PITERA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        CalculadoraMamasButton.setBackground(new java.awt.Color(153, 153, 255));
        CalculadoraMamasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reaccion-quimica.png"))); // NOI18N
        jPanel2.add(CalculadoraMamasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        InfoCalEsqui.setBackground(new java.awt.Color(255, 204, 153));
        InfoCalEsqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscando.png"))); // NOI18N
        jPanel2.add(InfoCalEsqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        InfoMemorama.setBackground(new java.awt.Color(255, 255, 153));
        InfoMemorama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscando.png"))); // NOI18N
        jPanel2.add(InfoMemorama, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        InfCalcPiteraMamas.setBackground(new java.awt.Color(255, 255, 153));
        InfCalcPiteraMamas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscando.png"))); // NOI18N
        jPanel2.add(InfCalcPiteraMamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        InfoQuizz.setBackground(new java.awt.Color(255, 255, 153));
        InfoQuizz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscando.png"))); // NOI18N
        jPanel2.add(InfoQuizz, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        InfAhorcado.setBackground(new java.awt.Color(255, 255, 153));
        InfAhorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscando.png"))); // NOI18N
        jPanel2.add(InfAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        InfoButton.setBackground(new java.awt.Color(0, 51, 153));
        InfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/info.png"))); // NOI18N
        jPanel2.add(InfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AhorcadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AhorcadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AhorcadoButtonActionPerformed

    private void QuizzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizzButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuizzButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AhorcadoButton;
    private javax.swing.JButton CalculadoraButton;
    private javax.swing.JButton CalculadoraMamasButton;
    private javax.swing.JButton InfAhorcado;
    private javax.swing.JButton InfCalcPiteraMamas;
    private javax.swing.JButton InfoButton;
    private javax.swing.JButton InfoCalEsqui;
    private javax.swing.JButton InfoMemorama;
    private javax.swing.JButton InfoQuizz;
    private javax.swing.JButton MemoramaButton;
    private javax.swing.JButton QuizzButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
